language: python

matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36

install:
  - pip install -r requirements_dev.txt
  - python setup.py install

script: tox -e ${TOXENV}

after_success:
  - codecov